# The base URL for your site. Should include the protocol (e.g., 'https://').
baseURL = 'https://example.org/'
# The title of your site.
title = 'Sleek Stream'
# The default language code for your site.
languageCode = "en-us"
DefaultContentLanguage = "en"

[module]

[[module.imports]]
path = 'github.com/hugomods/icons/vendors/bootstrap'

[[module.imports]]
path = 'github.com/hugomods/icons/vendors/font-awesome'

[[module.imports]]
path = 'github.com/hugomods/icons/vendors/simple-icons'
