# ======================================= #
# ============= Main Menu =============== #
# ======================================= #
[[mainmenu]]
name = "Home"
url = "/"
pre = "house-door"
weight = 1

[[mainmenu]]
name = "About"
url = "/about"
pre = 'person'
weight = 2

[[mainmenu]]
name = "Posts"
url = "/posts"
pre = 'file-earmark-text'
weight = 3

[[mainmenu]]
name = "Contact"
url = "/contact"
pre = 'phone'
weight = 4
