# ======================================= #
# ============= Main Menu =============== #
# ======================================= #
[[mainmenu]]
name = "Home"
url = "/"
pre = "house-door"
weight = 1

[[mainmenu]]
name = "About"
url = "/about"
pre = 'person'
weight = 2

[[mainmenu]]
name = "Posts"
url = "/posts"
pre = 'file-earmark-text'
weight = 3

[[mainmenu]]
name = "Contact"
url = "/contact"
pre = 'phone'
weight = 4

# ======================================= #
# ============ Footer Menu ============== #
# ======================================= #
[[footermenu]]
name = "Tags"
url = "/tags"
pre = ""
weight = 1

[[footermenu]]
name = "Categories"
url = "/categories"
pre = ""
weight = 2

[[footermenu]]
name = "Series"
url = "/series"
pre = ""
weight = 3

[[footermenu]]
name = "Authors"
url = "/authors"
pre = ""
weight = 4
