# Color Theme for site ('sleekstream' Default) ( 'terminal' 'fire' 'ocean' 'slate' 'autum' 'neon' 'avacado' 'princess' 'marvel' 'forest' 'noir' 'congo' 'blood')
colorScheme = ''
# Keywords associated with the site
keywords = ['site , template']
# Social media links
twitter = "@Armoghan12"
# Facebook Admins ID for Open Graph meta tag
facebookAdmins = "000000000000000"
# Facebook App ID for Open Graph meta tag
facebookAppID = "000000000000000"

[Custom]
Css = false # Disable custom CSS (set to true if you want to enable)
Js = false # Disable custom JavaScript (set to true if you want to enable)
