name: Auto Add Reviewers

on:
  pull_request:
    types:
      - opened

jobs:
  add_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Reviewers
        run: |
          # Use GitHub API to add reviewers here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
